name: financer
description: A Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  animated_text_kit: ^4.2.2
  flutter_verification_code: ^1.1.6
  flutter_share: ^2.0.0
  url_launcher: ^6.1.7
  algolia: ^1.1.1
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Audiowide-Regular
      fonts:
        - asset: assets/fonts/Audiowide-Regular.ttf
          weight: 900
